# Generated by Django 2.2 on 2020-04-09 14:15

from django.db import migrations, models
import webaccount.models


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0002_clientrequireddocuments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_personal_info',
            name='Number_of_subaccounts',
            field=models.IntegerField(default=0, validators=[webaccount.models.integerValidatorAccounts], verbose_name='Number of Sub-Accounts'),
        ),
    ]
