# Generated by Django 2.2 on 2020-04-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0002_auto_20200405_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequireddocuments',
            name='status',
            field=models.CharField(choices=[('None', 'None'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='None', max_length=10, verbose_name='Status'),
        ),
    ]
