# Generated by Django 2.2 on 2020-04-09 23:20

from django.db import migrations, models
import webaccount.models


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0003_auto_20200409_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_personal_info',
            name='package_price',
            field=models.IntegerField(default=0, validators=[webaccount.models.integerValidatorAccounts], verbose_name='Package Price'),
        ),
    ]
