# Generated by Django 2.2 on 2020-04-05 10:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import webaccount.models


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0003_auto_20200405_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_personal_info',
            name='CR',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='client_personal_info',
            name='Number_of_branches',
            field=models.IntegerField(default=0, validators=[webaccount.models.integerValidator], verbose_name='Number of Branches'),
        ),
        migrations.AlterField(
            model_name='client_personal_info',
            name='Number_of_employees',
            field=models.IntegerField(default=0, validators=[webaccount.models.integerValidator], verbose_name='Number of Employees'),
        ),
        migrations.AlterField(
            model_name='client_personal_info',
            name='Number_of_subaccounts',
            field=models.IntegerField(validators=[webaccount.models.integerValidator], verbose_name='Number of Sub-Accounts'),
        ),
        migrations.AlterField(
            model_name='client_personal_info',
            name='contact_number',
            field=models.CharField(default='0500000000', max_length=10, validators=[webaccount.models.phoneNumberValidator], verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='client_personal_info',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 5, 10, 7, 44, 292221, tzinfo=utc), verbose_name='Last Update'),
        ),
        migrations.AlterField(
            model_name='client_personal_info',
            name='package_price',
            field=models.IntegerField(validators=[webaccount.models.integerValidator], verbose_name='Package Price'),
        ),
        migrations.AlterField(
            model_name='relationmanager',
            name='contactNumber',
            field=models.CharField(default='', max_length=10, validators=[webaccount.models.phoneNumberValidator], verbose_name='Contact Number'),
        ),
    ]
