# Generated by Django 2.2 on 2020-04-12 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0004_auto_20200410_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_personal_info',
            name='sector',
            field=models.ForeignKey(error_messages={'blank': 'Sector can not be left as blank.', 'null': 'Sector Field is not selected'}, on_delete=django.db.models.deletion.CASCADE, to='webaccount.Sector', verbose_name='Sector'),
        ),
    ]
