# Generated by Django 2.2 on 2020-04-05 10:11

from django.db import migrations, models
import django.utils.timezone
import webaccount.models


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0004_auto_20200405_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_personal_info',
            name='Phone_Number',
            field=models.CharField(default='0500000000', max_length=10, validators=[webaccount.models.phoneNumberValidator], verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='client_personal_info',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Update'),
        ),
    ]
