# Generated by Django 2.2 on 2020-04-12 20:42

from django.db import migrations, models
import django.db.models.deletion
import webaccount.models


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0005_auto_20200413_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_personal_info',
            name='sector',
            field=models.ForeignKey(error_messages={'blank': 'Sector can not be left as blank.', 'null': 'Sector Field is not selected'}, on_delete=django.db.models.deletion.CASCADE, to='webaccount.Sector', validators=[webaccount.models.checkIntegrityError], verbose_name='Sector'),
        ),
    ]
