# Generated by Django 2.2 on 2020-04-05 15:31

from django.db import migrations, models
import webaccount.models


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0005_auto_20200405_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_personal_info',
            name='CR',
            field=models.CharField(default='0000000000', max_length=10, validators=[webaccount.models.convertToInteger], verbose_name='CR'),
        ),
        migrations.AlterField(
            model_name='client_personal_info',
            name='Phone_Number',
            field=models.CharField(default='0500000000', max_length=10, validators=[webaccount.models.phoneNumberValidator], verbose_name='Phone Number'),
        ),
    ]
