# Generated by Django 2.2 on 2020-04-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0007_auto_20200413_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_personal_info',
            name='Name',
            field=models.CharField(error_messages={'blank': 'Name field is empty.', 'null': 'Name field is empty.'}, max_length=300, verbose_name='Name'),
        ),
    ]
