# Generated by Django 2.2 on 2020-04-06 16:19

from django.db import migrations, models
import django.db.models.deletion
import webaccount.models


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0008_auto_20200405_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_personal_info',
            name='Number_of_branches',
            field=models.IntegerField(default=1, validators=[webaccount.models.integerValidator], verbose_name='Number of Branches'),
        ),
        migrations.AlterField(
            model_name='client_personal_info',
            name='Number_of_employees',
            field=models.IntegerField(default=1, validators=[webaccount.models.integerValidator], verbose_name='Number of Employees'),
        ),
        migrations.AlterField(
            model_name='client_personal_info',
            name='managerRelational',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webaccount.relationManager', verbose_name='RM'),
        ),
    ]
