# Generated by Django 2.2 on 2020-04-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0009_auto_20200413_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_personal_info',
            name='Email',
            field=models.EmailField(error_messages={'blank': 'Email field is empty.', 'null': 'Email field is empty.', 'unique': 'Already exists.'}, max_length=300, unique=True, verbose_name='Email'),
        ),
    ]
