# Generated by Django 2.2 on 2020-04-07 15:05

from django.db import migrations, models
import webaccount.models


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0009_auto_20200406_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_personal_info',
            name='Email',
            field=models.EmailField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='client_personal_info',
            name='Name',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='client_personal_info',
            name='Phone_Number',
            field=models.CharField(max_length=10, unique=True, validators=[webaccount.models.phoneNumberValidator], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='client_personal_info',
            name='Services',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='client_personal_info',
            name='company_name',
            field=models.CharField(max_length=300, verbose_name='Company Name'),
        ),
    ]
