# Generated by Django 2.2 on 2020-04-12 22:26

from django.db import migrations, models
import webaccount.models


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0010_auto_20200413_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_personal_info',
            name='Phone_Number',
            field=models.CharField(error_messages={'blank': 'Phone Number is required.', 'null': 'Phone Number is required.', 'unique': 'Already exists.'}, max_length=10, unique=True, validators=[webaccount.models.phoneNumberValidator], verbose_name='Phone Number'),
        ),
    ]
