# Generated by Django 2.2 on 2020-04-12 22:32

from django.db import migrations, models
import webaccount.models


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0011_auto_20200413_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_personal_info',
            name='CR',
            field=models.CharField(error_messages={'blank': 'CR is required.', 'null': 'CR is required.', 'unique': 'Already exists.'}, max_length=10, unique=True, validators=[webaccount.models.convertToInteger], verbose_name='CR'),
        ),
    ]
