# Generated by Django 2.2 on 2020-04-13 00:14

from django.db import migrations, models
import webaccount.models


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0013_auto_20200413_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_personal_info',
            name='Number_of_branches',
            field=models.IntegerField(default=1, error_messages={'blank': 'Number of Branches can not be left as blank.', 'null': 'Number of Branches Field is not entered'}, validators=[webaccount.models.integerValidator], verbose_name='Number of Branches'),
        ),
        migrations.AlterField(
            model_name='client_personal_info',
            name='Number_of_employees',
            field=models.IntegerField(default=1, error_messages={'blank': 'Number of Employees can not be left as blank.', 'null': 'Number of Employees Field is not entered'}, validators=[webaccount.models.integerValidator], verbose_name='Number of Employees'),
        ),
        migrations.AlterField(
            model_name='client_personal_info',
            name='Number_of_subaccounts',
            field=models.IntegerField(default=0, error_messages={'blank': 'Number of Sub-Accounts can not be left as blank.', 'null': 'Number of Sub-Accounts Field is not entered'}, validators=[webaccount.models.integerValidatorAccounts], verbose_name='Number of Sub-Accounts'),
        ),
        migrations.AlterField(
            model_name='client_personal_info',
            name='Services',
            field=models.CharField(error_messages={'blank': 'Services can not be left as blank.', 'null': 'Services Field is not entered'}, max_length=300, verbose_name='Services'),
        ),
        migrations.AlterField(
            model_name='client_personal_info',
            name='contact_number',
            field=models.CharField(error_messages={'blank': 'location is required.', 'null': 'location is required.'}, max_length=10, validators=[webaccount.models.phoneNumberValidator], verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='client_personal_info',
            name='package_price',
            field=models.IntegerField(default=0, error_messages={'blank': 'Package Price can not be left as blank.', 'null': 'Package Price Field is not entered'}, validators=[webaccount.models.integerValidatorAccounts], verbose_name='Package Price'),
        ),
        migrations.AlterField(
            model_name='client_personal_info',
            name='paymenStatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Overdue', 'Overdue'), ('Declined', 'Declined'), ('Paid', 'Paid')], default='Pending', error_messages={'blank': 'Subscription Status can not be left as blank.', 'null': 'Subscription Status Field is not entered'}, max_length=15, verbose_name='Subscription Status'),
        ),
    ]
