# Generated by Django 2.2.12 on 2020-04-22 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0017_auto_20200422_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsulatationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField(default=None, error_messages={'blank': 'Explanation is Rquired.'}, max_length=200, verbose_name='Explanation')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webaccount.Client_Personal_Info')),
            ],
        ),
        migrations.DeleteModel(
            name='Consulatation',
        ),
    ]
