# Generated by Django 2.2.12 on 2020-04-22 18:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0018_auto_20200422_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=None, error_messages={'blank': 'Name is required', 'unique': 'Name Already Exists.'}, max_length=100, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='consulatationrequest',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='consulatationrequest',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='New', max_length=100, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='consulatationrequest',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consulatationrequest',
            name='consultant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webaccount.ConsultantModel'),
        ),
    ]
