# Generated by Django 2.2.12 on 2020-04-22 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0019_auto_20200422_2332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulatationrequest',
            options={'ordering': ['-id'], 'verbose_name': 'Consultation Requests', 'verbose_name_plural': 'Consultation Requests'},
        ),
        migrations.AlterModelOptions(
            name='consultantmodel',
            options={'ordering': ['-id'], 'verbose_name': 'Consultation', 'verbose_name_plural': 'Consultations'},
        ),
    ]
