# Generated by Django 2.2.12 on 2020-04-22 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0021_auto_20200422_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulatationrequest',
            name='consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webaccount.ConsultantModel'),
        ),
    ]
