# Generated by Django 2.2.12 on 2020-04-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0022_auto_20200422_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulatationrequest',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Price'),
        ),
    ]
