# Generated by Django 2.2.12 on 2020-04-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0023_auto_20200422_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulatationrequest',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Confirmed', 'Confirmed'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='New', max_length=100, verbose_name='Status'),
        ),
    ]
