# Generated by Django 2.2.12 on 2020-04-23 08:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0024_auto_20200423_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulatationrequest',
            old_name='timestamp',
            new_name='created_timestamp',
        ),
        migrations.AddField(
            model_name='consulatationrequest',
            name='update_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
