# Generated by Django 2.2.12 on 2020-04-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0025_auto_20200423_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulatationrequest',
            name='client_paid',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, max_length=100, null=True, verbose_name='Client Paid Amound'),
        ),
        migrations.AddField(
            model_name='consulatationrequest',
            name='client_paid_all_amound',
            field=models.BooleanField(default=False, verbose_name='Paid All Amount'),
        ),
    ]
