# Generated by Django 2.2.12 on 2020-04-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webaccount', '0028_auto_20200423_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulatationrequest',
            name='feedbackFile',
            field=models.FileField(blank=True, upload_to='uploads/feedback/%Y/%m/%d/', verbose_name='Feedback Document'),
        ),
    ]
